"""
Shared data for all bacterial identification timeline figures.
Six eras from Observation & Morphology (1670s) through Dynamic Phenotyping (2024–2025).
"""

ERA_DATA = [
    {
        "id": 1,
        "era": "Observation &\nMorphology",
        "era_inline": "Observation & Morphology",
        "timeframe": "1670s – 1880s",
        "milestone": "Microscopy, pure culture,\n& Gram staining",
        "milestone_inline": "Microscopy, pure culture, & Gram staining",
        "paradigm": "Established visual characteristics\nand fundamental classification logic.",
        "paradigm_inline": "Established visual characteristics and fundamental classification logic.",
        "reference": "Leeuwenhoek (1670s); Gram (1884); Koch",
        "color": "#5B4A8A",
        "light": "#EDE8F5",
        "icon": "microscope",
        "year_start": 1670,
        "year_end": 1890,
    },
    {
        "id": 2,
        "era": "Biochemical\nProfiling",
        "era_inline": "Biochemical Profiling",
        "timeframe": "Mid-1900s",
        "milestone": "Metabolic screening\n(fermentation, catalase)",
        "milestone_inline": "Metabolic screening (fermentation, catalase)",
        "paradigm": "Shifted focus from static morphology\nto active metabolic phenotypes.",
        "paradigm_inline": "Shifted focus from static morphology to active metabolic phenotypes.",
        "reference": "Bergey's Manual; Clarridge (2004)",
        "color": "#1B7B8A",
        "light": "#D5EEF0",
        "icon": "flask",
        "year_start": 1920,
        "year_end": 1975,
    },
    {
        "id": 3,
        "era": "16S rRNA\nRevolution",
        "era_inline": "16S rRNA Revolution",
        "timeframe": "1970s – 2000s",
        "milestone": "Phylogeny via 16S rRNA\nsequencing",
        "milestone_inline": "Phylogeny via 16S rRNA sequencing",
        "paradigm": "Replaced phenotypic approximation with\nexact genotypic ID; unlocked unculturable taxa.",
        "paradigm_inline": "Replaced phenotypic approximation with exact genotypic ID; unlocked unculturable taxa.",
        "reference": "Woese et al. (1977)",
        "color": "#2D8C5A",
        "light": "#D5EFDF",
        "icon": "dna",
        "year_start": 1977,
        "year_end": 2010,
    },
    {
        "id": 4,
        "era": "Genomic\nResolution",
        "era_inline": "Genomic Resolution",
        "timeframe": "2010s",
        "milestone": "Whole Genome\nSequencing (WGS)",
        "milestone_inline": "Whole Genome Sequencing (WGS)",
        "paradigm": "Moved from single-gene identification to\nsingle-base, strain-level genomic resolution.",
        "paradigm_inline": "Moved from single-gene identification to single-base, strain-level genomic resolution.",
        "reference": "Clinical validation reviews",
        "color": "#C87A20",
        "light": "#FAE8D0",
        "icon": "genome",
        "year_start": 2010,
        "year_end": 2020,
    },
    {
        "id": 5,
        "era": "High-Dimensional\nAI",
        "era_inline": "High-Dimensional AI",
        "timeframe": "2020s+",
        "milestone": "ML-driven classification\n& clustering",
        "milestone_inline": "ML-driven classification & clustering",
        "paradigm": "Transitioned from human-led sequence analysis\nto AI-driven pattern recognition.",
        "paradigm_inline": "Transitioned from human-led sequence analysis to AI-driven pattern recognition.",
        "reference": "Recent ML classification literature",
        "color": "#2155A0",
        "light": "#D0DFF0",
        "icon": "ai",
        "year_start": 2018,
        "year_end": 2024,
    },
    {
        "id": 6,
        "era": "Dynamic\nPhenotyping",
        "era_inline": "Dynamic Phenotyping",
        "timeframe": "2024 – 2025",
        "milestone": "AI models on\ngrowth kinetics",
        "milestone_inline": "AI models on growth kinetics",
        "paradigm": "Recontextualized time-series growth data\n(OD curves) as high-dimensional, predictive datasets.",
        "paradigm_inline": "Recontextualized time-series growth data (OD curves) as high-dimensional, predictive datasets.",
        "reference": "Current Work / Proposed Paradigm",
        "color": "#8B3A9B",
        "light": "#F0D5F0",
        "icon": "growth_curve",
        "year_start": 2024,
        "year_end": 2026,
    },
]
